### ISSUE TITLE
(IMPORT FAILED)

### ISSUE THREAD

**Issue by kort3s** [XLabs-AI/x-flux-comfyui#10]
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 354, in <module>
    from optimum.quanto import requantize
ModuleNotFoundError: No module named 'optimum.quanto'

Cannot import E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui module for custom nodes: No module named 'optimum.quanto'

**Comment by Vovanm88** [comment]
update pls, it was a bug only for 3 minutes :(

**Comment by kort3s** [comment]
Cheers, but I updated but same error still. I did python setup.py too
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 354, in <module>
    from optimum.quanto import requantize
ModuleNotFoundError: No module named 'optimum.quanto'

Cannot import E:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui module for custom nodes: No module named 'optimum.quanto'

**Comment by tarunm14** [comment]
```
pip install optimum-quanto
``` 

fixed the issue

**Comment by Vovanm88** [comment]
>     from optimum.quanto import requantize
> ModuleNotFoundError: No module named 'optimum.quanto'
> 
> Cannot import E:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui module for custom nodes: No module named 'optimum.quanto'

It's kinda strange, we deleted this 

Try delete all folder x-flux and clone it again?

**Comment by kort3s** [comment]
I deleted folder and clone it again and removed quanto from  python_embebed/lib/site-package and now it works ! ;)  thank you very much for the Help

**Comment by YT-kexuejia** [comment]
pip install optimum
pip install optimum-quanto
worked

**Comment by yogotatara3** [comment]
when I install optimum quanto it downloads a different torch version and kills my load up and port.
I'm on the newest comfy update

**Comment by Vovanm88** [comment]
I think fixed rn for lastest version
