### ISSUE TITLE
 (IMPORT FAILED): L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui

### ISSUE THREAD

**Issue by yifenglv46** [XLabs-AI/x-flux-comfyui#122]
L:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 12287 MB, total RAM 32726 MB
pytorch version: 2.3.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: L:\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints K:\stable-diffusion-webui2\models/Stable-diffusion
Adding extra search path configs K:\stable-diffusion-webui2\models/Stable-diffusion
Adding extra search path vae K:\stable-diffusion-webui2\models/VAE
Adding extra search path loras K:\stable-diffusion-webui2\models/Lora
Adding extra search path loras K:\stable-diffusion-webui2\models/LyCORIS
Adding extra search path upscale_models K:\stable-diffusion-webui2\models/ESRGAN
Adding extra search path upscale_models K:\stable-diffusion-webui2\models/RealESRGAN
Adding extra search path upscale_models K:\stable-diffusion-webui2\models/SwinIR
Adding extra search path embeddings K:\stable-diffusion-webui2\embeddings
Adding extra search path hypernetworks K:\stable-diffusion-webui2\models/hypernetworks
Adding extra search path controlnet K:\stable-diffusion-webui2\extensions\sd-webui-controlnet\models\
Traceback (most recent call last):
  File "L:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 17, in <module>
    from .xflux.src.flux.util import (configs, load_ae, load_clip,
  File "L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\xflux\src\flux\util.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui

**Comment by devthyg** [comment]
do you find solution for this
