### ISSUE TITLE
't5xxl' error (gguf model)

### ISSUE THREAD

**Issue by sitzbrau** [XLabs-AI/x-flux-comfyui#140]
### CLIPTextEncodeFlux 't5xxl' error (gguf model)

I've just straight loaded the ip_adapter_workflow.json from hugging face.
Changed with the Model loader and CLIP Loader with the GGUF ones.
![image](https://github.com/user-attachments/assets/a150fe2f-61db-4b99-8325-a66b26dd35e4)

When i run the process appaears this error
![image](https://github.com/user-attachments/assets/d3995a49-0a8e-4384-8156-3a6337b9417d)

I don't think it's a problem to use **gguf templates**, they are currently supported  as @Anghellia wrote before

**Any help appreciated**

### Report
```
# ComfyUI Error Report
## Error Details
- **Node Type:** CLIPTextEncodeFlux
- **Exception Type:** KeyError
- **Exception Message:** 't5xxl'
## Stack Trace

  File "/home/ubuntu/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/ubuntu/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/home/ubuntu/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/ubuntu/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/home/ubuntu/ComfyUI/comfy_extras/nodes_flux.py", line 19, in encode
    tokens["t5xxl"] = clip.tokenize(t5xxl)["t5xxl"]

```
## System Information
- **ComfyUI Version:** v0.2.3-13-g7390ff3
- **Arguments:** main.py --listen --highvram
- **OS:** posix
- **Python Version:** 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA L4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 23690805248
  - **VRAM Free:** 23489282048
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-17 10:41:55,340 - root - INFO - Total VRAM 22593 MB, total RAM 30883 MB
2024-10-17 10:41:55,340 - root - INFO - pytorch version: 2.4.1+cu118
2024-10-17 10:41:56,392 - root - INFO - xformers version: 0.0.28.post1
2024-10-17 10:41:56,393 - root - INFO - Set vram state to: HIGH_VRAM
2024-10-17 10:41:56,393 - root - INFO - Device: cuda:0 NVIDIA L4 : cudaMallocAsync
2024-10-17 10:41:56,466 - root - INFO - Using xformers cross attention
2024-10-17 10:41:57,008 - root - INFO - [Prompt Server] web root: /home/ubuntu/ComfyUI/web
2024-10-17 10:41:59,117 - root - INFO - 
Import times for custom nodes:
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/websocket_image_save.py
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_photomakerV2_native
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ControlAltAI-Nodes
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-PhotoMaker-Plus
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/rgthree-comfy
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-GGUF
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-10-17 10:41:59,117 - root - INFO -    0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager
2024-10-17 10:41:59,117 - root - INFO -    0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/x-flux-comfyui
2024-10-17 10:41:59,117 - root - INFO -    0.4 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Easy-Use
2024-10-17 10:41:59,117 - root - INFO -    0.6 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI_InstantID
2024-10-17 10:41:59,117 - root - INFO -    0.7 seconds: /home/ubuntu/ComfyUI/custom_nodes/was-node-suite-comfyui
2024-10-17 10:41:59,118 - root - INFO - 
2024-10-17 10:41:59,126 - root - INFO - Starting server

2024-10-17 10:41:59,127 - root - INFO - To see the GUI go to: http://0.0.0.0:8188
2024-10-17 10:41:59,127 - root - INFO - To see the GUI go to: http://[::]:8188
2024-10-17 10:43:31,830 - root - INFO - got prompt
2024-10-17 10:43:32,065 - root - INFO - Using xformers attention in VAE
2024-10-17 10:43:32,066 - root - INFO - Using xformers attention in VAE
2024-10-17 10:43:39,801 - root - WARNING - clip missing: ['text_model.embeddings.token_embedding.weight', 'text_model.embeddings.position_embedding.weight', 'text_model.encoder.layers.0.layer_norm1.weight', 'text_model.encoder.layers.0.layer_norm1.bias', 'text_model.encoder.layers.0.layer_norm2.weight', 'text_model.encoder.layers.0.layer_norm2.bias', 'text_model.encoder.layers.1.layer_norm1.weight', 'text_model.encoder.layers.1.layer_norm1.bias', 'text_model.encoder.layers.1.layer_norm2.weight', 'text_model.encoder.layers.1.layer_norm2.bias', 'text_model.encoder.layers.2.layer_norm1.weight', 'text_model.encoder.layers.2.layer_norm1.bias', 'text_model.encoder.layers.2.layer_norm2.weight', 'text_model.encoder.layers.2.layer_norm2.bias', 'text_model.encoder.layers.3.layer_norm1.weight', 'text_model.encoder.layers.3.layer_norm1.bias', 'text_model.encoder.layers.3.layer_norm2.weight', 'text_model.encoder.layers.3.layer_norm2.bias', 'text_model.encoder.layers.4.layer_norm1.weight', 'text_model.encoder.layers.4.layer_norm1.bias', 'text_model.encoder.layers.4.layer_norm2.weight', 'text_model.encoder.layers.4.layer_norm2.bias', 'text_model.encoder.layers.5.layer_norm1.weight', 'text_model.encoder.layers.5.layer_norm1.bias', 'text_model.encoder.layers.5.layer_norm2.weight', 'text_model.encoder.layers.5.layer_norm2.bias', 'text_model.encoder.layers.6.layer_norm1.weight', 'text_model.encoder.layers.6.layer_norm1.bias', 'text_model.encoder.layers.6.layer_norm2.weight', 'text_model.encoder.layers.6.layer_norm2.bias', 'text_model.encoder.layers.7.layer_norm1.weight', 'text_model.encoder.layers.7.layer_norm1.bias', 'text_model.encoder.layers.7.layer_norm2.weight', 'text_model.encoder.layers.7.layer_norm2.bias', 'text_model.encoder.layers.8.layer_norm1.weight', 'text_model.encoder.layers.8.layer_norm1.bias', 'text_model.encoder.layers.8.layer_norm2.weight', 'text_model.encoder.layers.8.layer_norm2.bias', 'text_model.encoder.layers.9.layer_norm1.weight', 'text_model.encoder.layers.9.layer_norm1.bias', 'text_model.encoder.layers.9.layer_norm2.weight', 'text_model.encoder.layers.9.layer_norm2.bias', 'text_model.encoder.layers.10.layer_norm1.weight', 'text_model.encoder.layers.10.layer_norm1.bias', 'text_model.encoder.layers.10.layer_norm2.weight', 'text_model.encoder.layers.10.layer_norm2.bias', 'text_model.encoder.layers.11.layer_norm1.weight', 'text_model.encoder.layers.11.layer_norm1.bias', 'text_model.encoder.layers.11.layer_norm2.weight', 'text_model.encoder.layers.11.layer_norm2.bias', 'text_model.final_layer_norm.weight', 'text_model.final_layer_norm.bias']
2024-10-17 10:43:39,802 - root - ERROR - !!! Exception during processing !!! 't5xxl'
2024-10-17 10:43:39,803 - root - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ubuntu/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ubuntu/ComfyUI/comfy_extras/nodes_flux.py", line 19, in encode
    tokens["t5xxl"] = clip.tokenize(t5xxl)["t5xxl"]
KeyError: 't5xxl'

2024-10-17 10:43:39,803 - root - INFO - Prompt executed in 7.75 seconds
2024-10-17 10:47:24,323 - root - INFO - got prompt
2024-10-17 10:47:24,329 - root - ERROR - !!! Exception during processing !!! 't5xxl'
2024-10-17 10:47:24,329 - root - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ubuntu/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ubuntu/ComfyUI/comfy_extras/nodes_flux.py", line 19, in encode
    tokens["t5xxl"] = clip.tokenize(t5xxl)["t5xxl"]
KeyError: 't5xxl'

2024-10-17 10:47:24,329 - root - INFO - Prompt executed in 0.00 seconds
```

**Comment by Solarish** [comment]
![{7662F880-BB7C-4F2D-AEC7-F553DDAAB5CE}](https://github.com/user-attachments/assets/b34601c2-efd1-4037-9a4e-60278924ac0c)

use 'Flux' in Type
