### ISSUE TITLE
KeyError: 'guidance'

### ISSUE THREAD

**Issue by dinusha94** [XLabs-AI/x-flux-comfyui#15]
I am getting the following error while running the pipeline in comfyUI

Traceback (most recent call last):
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/usr_9110799_ulta_com/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 275, in sampling
    guidance=conditioning[0][1]['guidance']
KeyError: 'guidance'

Here is my workflow

![image](https://github.com/user-attachments/assets/09a74f30-8ef7-46cc-a625-6186843ce8e2)

**Comment by Vovanm88** [comment]
You use defalut "clip text encode" node, which is not fully supported by flux model, better use dual clip loader and flux encoder like in our workflows, but we will fix it then (but the gen quality will be not so good)

**Comment by dinusha94** [comment]
@Vovanm88 are there any CUDA memory requirements for the xlabs sampler, I am getting the following error while running the sampler. but in my machine, I was able to successfully run the flux text to image workflows.

I am using Tesla T4 16GB GPU

error

```
Exception in thread Thread-4 (prompt_worker):
Traceback (most recent call last):
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/usr_9110799_ulta_com/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 310, in sampling
    inmodel.diffusion_model.to(device)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 13.87 GiB
Requested               : 27.00 MiB
Device limit            : 14.76 GiB
Free (according to CUDA): 32.75 MiB
PyTorch limit (set by user-supplied memory fraction) 
```
