### ISSUE TITLE
Python OpenCV library missing, resulting in failure

### ISSUE THREAD

**Issue by AndreTelevise** [XLabs-AI/x-flux-comfyui#22]
Python OpenCV library not registering, resulting in a failure to load XlabsSampler and FluxLoraLoader. Is it because I also installed other modules as well for other workflows? Is it because I'm using ComfyUI Portable? Is it because of something else? I'd be happy to hear an answer.

The debug:
`Traceback (most recent call last):
  File "C:\Users\Andre\comfyui\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Andre\comfyui\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Andre\comfyui\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 12, in <module>
    from .xflux.src.flux.util import (configs, load_ae, load_clip,
  File "C:\Users\Andre\comfyui\ComfyUI\custom_nodes\x-flux-comfyui\xflux\src\flux\util.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

**Comment by Vovanm88** [comment]
pip install opencv-python
