### ISSUE TITLE
Can't load a lora trained from civitai.

### ISSUE THREAD

**Issue by dchatel** [XLabs-AI/x-flux-comfyui#29]
Using the lora workflow provided on x-flux-comfyui to load and use [a flux lora trained on civitai](https://github.com/user-attachments/files/16642516/occsanflux.zip), I get this error:

```
!!! Exception during processing !!! list index out of range
Traceback (most recent call last):
  File "G:\ai\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ai\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 117, in loadmodel
    checkpoint, lora_rank = load_flux_lora(os.path.join(dir_xlabs_loras, lora_name))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 59, in load_flux_lora
    a1 = sorted(list(checkpoint[list(checkpoint.keys())[0]].shape))[0]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
This is due to the following:
![image](https://github.com/user-attachments/assets/fb6697a5-5cbe-4a65-a9ff-b88f41a19d1c)
Basically, that first tensor in the checkpoint is a scalar, so it has no dimension, thus you can't iterate over its dimensions (obviously).

But if I do a quick "fix" like this:
```
def load_flux_lora(path):
    if path is not None:
        if '.safetensors' in path:
            checkpoint = load_safetensors(path)
        else:
            checkpoint = torch.load(path, map_location='cpu')
    else:
        checkpoint = None
        print("Invalid path")
    if len(checkpoint[list(checkpoint.keys())[0]].shape) > 0:
        a1 = sorted(list(checkpoint[list(checkpoint.keys())[0]].shape))[0]
        a2 = sorted(list(checkpoint[list(checkpoint.keys())[1]].shape))[0]
        if a1==a2:
            return checkpoint, int(a1)
    return checkpoint, 16
```
Then I get the following error:
```
!!! Exception during processing !!! Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
        Missing key(s) in state_dict: "qkv_lora1.down.weight", "qkv_lora1.up.weight", "proj_lora1.down.weight", "proj_lora1.up.weight", "qkv_lora2.down.weight", "qkv_lora2.up.weight", "proj_lora2.down.weight", "proj_lora2.up.weight".
Traceback (most recent call last):
  File "G:\ai\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ai\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 140, in loadmodel
    lora_attn_procs[name].load_state_dict(lora_state_dict)
  File "C:\Users\dchat\miniconda3\envs\comfy\Lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
        Missing key(s) in state_dict: "qkv_lora1.down.weight", "qkv_lora1.up.weight", "proj_lora1.down.weight", "proj_lora1.up.weight", "qkv_lora2.down.weight", "qkv_lora2.up.weight", "proj_lora2.down.weight", "proj_lora2.up.weight".
```

**Comment by Vovanm88** [comment]
Sooo, can you send me you LoRA so I do nodes compatible with this?

**Comment by dchatel** [comment]
Well, it's in the zip file I attached to the original message, under the link caption "[a flux lora trained on civitai](https://github.com/user-attachments/files/16642516/occsanflux.zip)".

**Comment by barnaclejive** [comment]
I have the same error using a Lora I trained myself using [ai-toolkit](https://github.com/ostris/ai-toolkit/).

```
!!! Exception during processing !!! Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
        Missing key(s) in state_dict: "qkv_lora1.down.weight", "qkv_lora1.up.weight", "proj_lora1.down.weight", "proj_lora1.up.weight", "qkv_lora2.down.weight", "qkv_lora2.up.weight", "proj_lora2.down.weight", "proj_lora2.up.weight".
Traceback (most recent call last):
  File "C:\Users\foo\ai\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\foo\ai\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\foo\ai\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\foo\ai\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Users\foo\ai\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 153, in loadmodel
    lora_attn_procs[name].load_state_dict(lora_state_dict)
  File "C:\Users\foo\ai\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
        Missing key(s) in state_dict: "qkv_lora1.down.weight", "qkv_lora1.up.weight", "proj_lora1.down.weight", "proj_lora1.up.weight", "qkv_lora2.down.weight", "qkv_lora2.up.weight", "proj_lora2.down.weight", "proj_lora2.up.weight".
```

**Comment by balala8** [comment]
> I have the same error using a Lora I trained myself using [ai-toolkit](https://github.com/ostris/ai-toolkit/).
> 
> ```
> !!! Exception during processing !!! Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
>         Missing key(s) in state_dict: "qkv_lora1.down.weight", "qkv_lora1.up.weight", "proj_lora1.down.weight", "proj_lora1.up.weight", "qkv_lora2.down.weight", "qkv_lora2.up.weight", "proj_lora2.down.weight", "proj_lora2.up.weight".
> Traceback (most recent call last):
>   File "C:\Users\foo\ai\ComfyUI\execution.py", line 317, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "C:\Users\foo\ai\ComfyUI\execution.py", line 192, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>   File "C:\Users\foo\ai\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "C:\Users\foo\ai\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>   File "C:\Users\foo\ai\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 153, in loadmodel
>     lora_attn_procs[name].load_state_dict(lora_state_dict)
>   File "C:\Users\foo\ai\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
> RuntimeError: Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
>         Missing key(s) in state_dict: "qkv_lora1.down.weight", "qkv_lora1.up.weight", "proj_lora1.down.weight", "proj_lora1.up.weight", "qkv_lora2.down.weight", "qkv_lora2.up.weight", "proj_lora2.down.weight", "proj_lora2.up.weight".
> ```

Using the normal Lora model loader will not report an error
