### ISSUE TITLE
ModuleNotFoundError: No module named 'x-flux-comfyui.xflux'

### ISSUE THREAD

**Issue by Beamhi** [XLabs-AI/x-flux-comfyui#3]
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 12, in <module>
    from .xflux.src.flux.util import (configs, load_ae, load_clip,
ModuleNotFoundError: No module named 'x-flux-comfyui.xflux'

**Comment by gradient-diffusion** [comment]
You not install the x-flux
Go to  ComfyUI/custom_nodes/x-flux-comfyui/ and run python setup.py

**Comment by Beamhi** [comment]
thanks
