### ISSUE TITLE
Error running lora workflow

### ISSUE THREAD

**Issue by gaboprieto** [XLabs-AI/x-flux-comfyui#33]
Hello, I have done all the steps on the readme without error.

When trying to run the lora workflow with the furry lora from the example, and all the loras from the lora-collection repo listed in the readme.

```
Is model already patched? False
We are patching diffusion model, be patient please
!!! Exception during processing !!! 'Linear' object has no attribute 'out_features'
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 121, in loadmodel
    patches=FluxUpdateModules(tyanochky, pbar)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\utils.py", line 78, in FluxUpdateModules
    patches[f"double_blocks.{i}"]=CopyDSB(flux_model.diffusion_model.double_blocks[i])
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\utils.py", line 16, in CopyDSB
    mlp_hidden_dim  = tyan.img_mlp[0].out_features
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'out_features'

Prompt executed in 0.02 seconds
```

**Comment by Vovanm88** [comment]
What model do you use in diffusion loader?

**Comment by gaboprieto** [comment]
> What model do you use in diffusion loader?

Q_4_0.gguf

**Comment by gaboprieto** [comment]
Update: is happening with ipadapter too

**Comment by qlxxkj** [comment]
I meet the same issues

**Comment by omarei-omoto** [comment]
same

**Comment by Vovanm88** [comment]
Yes, but it not so easy so now in progress...
