### ISSUE TITLE
error: load flux lora-workflow

### ISSUE THREAD

**Issue by qlxxkj** [XLabs-AI/x-flux-comfyui#49]
![image](https://github.com/user-attachments/assets/58e90550-2353-4d72-865f-c8e7771fe3ba)

Is model already patched? False
!!! Exception during processing !!! Allocation on device 
Traceback (most recent call last):
  File "/home/hawk/sd/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/hawk/sd/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/hawk/sd/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/hawk/sd/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/hawk/sd/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 116, in loadmodel
    bi.model.to(device)
  File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/hawk/sd/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
torch.OutOfMemoryError: Allocation on device 

Got an OOM, unloading all loaded models.
Prompt executed in 3.81 seconds

**Comment by DigitalBeer** [comment]
I'm also having this issue. I'm using [flux1-dev-q8_0.gguf from city96 on Hugging Face](https://huggingface.co/city96/FLUX.1-dev-gguf/tree/main)

and the [Amateur Photography Lora from Civitai](https://civitai.com/models/652699/amateur-photography-flux-dev?modelVersionId=730225)

Doesn't seem to be all Lora's though as other Flux Dev specific ones seem to work fine such as 

[flux_realism_lora on Civitai](https://civitai.com/models/631986/xlabs-flux-realism-lora?modelVersionId=706528)
[boreal-flux-dev-lora-v04_1000_steps on Civitai](https://civitai.com/models/639937/boreal-fd-boring-reality-flux-dev-lora?modelVersionId=715729)

`Error occurred when executing SamplerCustomAdvanced:

Allocation on device

File "D:\aitools\ComfyUI\ComfyUI\execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "D:\aitools\ComfyUI\ComfyUI\execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "D:\aitools\ComfyUI\ComfyUI\execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "D:\aitools\ComfyUI\ComfyUI\execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "D:\aitools\ComfyUI\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 612, in sample
samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
File "D:\aitools\ComfyUI\ComfyUI\comfy\samplers.py", line 706, in sample
self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
File "D:\aitools\ComfyUI\ComfyUI\comfy\sampler_helpers.py", line 66, in prepare_sampling
comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
File "D:\aitools\ComfyUI\ComfyUI\comfy\model_management.py", line 535, in load_models_gpu
cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
File "D:\aitools\ComfyUI\ComfyUI\comfy\model_management.py", line 322, in model_load
raise e
File "D:\aitools\ComfyUI\ComfyUI\comfy\model_management.py", line 318, in model_load
self.real_model = self.model.patch_model(device_to=patch_model_to, lowvram_model_memory=lowvram_model_memory, load_weights=load_weights, force_patch_weights=force_patch_weights)
File "D:\aitools\ComfyUI\ComfyUI\comfy\model_patcher.py", line 428, in patch_model
self.load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights, full_load=full_load)
File "D:\aitools\ComfyUI\ComfyUI\comfy\model_patcher.py", line 394, in load
self.patch_weight_to_device(weight_key, device_to=device_to)
File "D:\aitools\ComfyUI\ComfyUI\comfy\model_patcher.py", line 333, in patch_weight_to_device
out_weight = comfy.float.stochastic_rounding(out_weight, weight.dtype)
File "D:\aitools\ComfyUI\ComfyUI\comfy\float.py", line 59, in stochastic_rounding
return value.to(dtype=dtype)
File "D:\aitools\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 23, in to
new = super().to(*args, **kwargs)
File "C:\Users\matde\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_tensor.py", line 1443, in __torch_function__
ret = func(*args, **kwargs)`

**Comment by imperatrona** [comment]
got the same error and found that you can use default `Load Lora` instead of `Load Flux Lora` and everything will work perfectly
![Screenshot 2024-08-26 at 13 06 07](https://github.com/user-attachments/assets/61766322-f08c-4bdd-802a-74839ed872f5)

**Comment by thomastraum** [comment]
would be good to get the convert script to convert them. 
I tried this one here but it doesnt seem to work anymore. https://huggingface.co/comfyanonymous/flux_RealismLora_converted_comfyui/blob/main/convert.py
