### ISSUE TITLE
For the xlab sampler latent input cant we use the VAE Encode ?

### ISSUE THREAD

**Issue by dinusha94** [XLabs-AI/x-flux-comfyui#69]
when using it I get the following error

```
got prompt
!!! Exception during processing !!!  Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
 Input tensor shape: torch.Size([1, 16, 183, 122]). Additional info: {'ph': 2, 'pw': 2}.
 Shape mismatch, can't divide axis of length 183 in chunks of 2
Traceback (most recent call last):
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/einops/einops.py", line 523, in reduce
    return _apply_recipe(
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/einops/einops.py", line 234, in _apply_recipe
    init_shapes, axes_reordering, reduced_axes, added_axes, final_shapes, n_axes_w_added = _reconstruct_from_shape(
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/einops/einops.py", line 187, in _reconstruct_from_shape_uncached
    raise EinopsError(f"Shape mismatch, can't divide axis of length {length} in chunks of {known_product}")
einops.EinopsError: Shape mismatch, can't divide axis of length 183 in chunks of 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/usr_9110799_ulta_com/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/usr_9110799_ulta_com/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 368, in sampling
    x = denoise_controlnet(
  File "/home/usr_9110799_ulta_com/ComfyUI/custom_nodes/x-flux-comfyui/sampling.py", line 250, in denoise_controlnet
    orig_image = rearrange(orig_image, "b c (h ph) (w pw) -> b (h w) (c ph pw)", ph=2, pw=2).to(img.device, dtype = img.dtype)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "/home/usr_9110799_ulta_com/.pyenv/versions/3.10.6/envs/venv/lib/python3.10/site-packages/einops/einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
 Input tensor shape: torch.Size([1, 16, 183, 122]). Additional info: {'ph': 2, 'pw': 2}.
 Shape mismatch, can't divide axis of length 183 in chunks of 2
```

**Comment by dinusha94** [comment]
I was using a different resolution, need to use 1024x1024
