### ISSUE TITLE
Excuse me, how to fix the error that occurs when executing setup.py?

### ISSUE THREAD

**Issue by Smirk-CAF** [XLabs-AI/x-flux-comfyui#8]
PS E:\CAF\ComfyUI_windows_portable\python_embeded> .\python.exe E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\setup.py
移动了　        1 个目录。
Requirement already satisfied: GitPython in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from -r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 1)) (3.1.43)
Requirement already satisfied: torch==2.4.0 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from -r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: torchvision==0.19.0 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from -r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 3)) (0.19.0)
Requirement already satisfied: filelock in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (3.15.3)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (4.12.2)
Requirement already satisfied: sympy in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (1.13.1)
Requirement already satisfied: networkx in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (3.3)
Requirement already satisfied: jinja2 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (3.1.4)
Requirement already satisfied: fsspec in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (2024.6.0)
Requirement already satisfied: numpy<2 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torchvision==0.19.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from torchvision==0.19.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 3)) (9.5.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from GitPython->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 1)) (4.0.11)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->GitPython->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 1)) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch==2.4.0->-r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/requirements.txt (line 2)) (1.3.0)

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: C:\Users\AIGC\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip
Requirement already satisfied: accelerate==0.30.1 in c:\users\aigc\appdata\local\programs\python\python311\lib\site-packages (from -r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/xflux/requirements.txt (line 1)) (0.30.1)
Collecting deepspeed==0.14.4 (from -r E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui/xflux/requirements.txt (line 2))
  Using cached deepspeed-0.14.4.tar.gz (1.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      Traceback (most recent call last):
        File "C:\Users\AIGC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\AIGC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\AIGC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\AIGC\AppData\Local\Temp\pip-build-env-w1x_q0cm\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\AIGC\AppData\Local\Temp\pip-build-env-w1x_q0cm\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\AIGC\AppData\Local\Temp\pip-build-env-w1x_q0cm\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\AIGC\AppData\Local\Temp\pip-build-env-w1x_q0cm\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 149, in <module>
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: C:\Users\AIGC\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip
Succesfully installed

**Comment by Vovanm88** [comment]
try to open xlabs/requirements.txt and manually install dependencies after deepspeed, its unnecessary for inference, but need to train, so nodes should work without it

**Comment by Smirk-CAF** [comment]
> 尝试打开 xlabs/requirements.txt 并在 deepspeed 之后手动安装依赖项，这对于推理来说是不必要的，但需要训练，所以节点应该在没有它的情况下工作
Thank you very much for your answer,
The new error shows that the local python environment path is not the python environment of ComfyUI, is it caused by my environment variables?
The following error message is displayed:

PS E:\CAF\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\xflux> E:\CAF\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt --upgrade
Requirement already satisfied: accelerate==0.30.1 in e:\caf\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (0.30.1)
Collecting deepspeed==0.14.4 (from -r requirements.txt (line 2))
  Downloading deepspeed-0.14.4.tar.gz (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 874.2 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\AIGC\AppData\Local\Temp\pip-install-4b4g2bq1\deepspeed_a06aa62f61ff401d88bb91f5ae432462\setup.py", line 38, in <module>
          from op_builder import get_default_compute_capabilities, OpBuilder
      ModuleNotFoundError: No module named 'op_builder'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by gradient-diffusion** [comment]
you can not install deepspeed

**Comment by Smirk-CAF** [comment]
Yes，it may be that Windows does not currently support triton and cannot install deepspeed.

> you can not install deepspeed

**Comment by gradient-diffusion** [comment]
fixed

**Comment by gradient-diffusion** [comment]
try again

**Comment by Smirk-CAF** [comment]
When running the setup.py, the first prompt is that the system cannot find the specified file. It's normal to enforce dependencies.

**Comment by Smirk-CAF** [comment]
The problem has been solved.
My steps:
Re-download x-flux-comfyui and install dependencies.
Then download x-flux and put it in the x-flux-comfyui directory. After running the dependencies, it can be used normally.
