### ISSUE TITLE
Error occurred when executing ApplyFluxIPAdapter with mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by Johnz86** [XLabs-AI/x-flux-comfyui#83]
I updated to latest comfyui today and installed latest plugin right now. 

On my first run of basic workflow with ApplyFluxIPAdapter I get following error.

```
Prompt executed in 8.85 seconds
got prompt
Is model already patched? True
Using old vit clip
Model already updated
!!! Exception during processing !!! mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x16384)
Traceback (most recent call last):
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 529, in applymodel
    ip_projes = ip_adapter_flux['ip_adapter_proj_model'](out.to(ip_projes_dev, dtype=torch.bfloat16)).to(device, dtype=torch.bfloat16)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\custom_nodes\x-flux-comfyui\layers.py", line 283, in forward
    clip_extra_context_tokens = self.proj(embeds).reshape(
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Programovanie\Python\stable-diffusion-web\ComfyUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1280 and 768x16384)

Prompt executed in 15.25 seconds
```
This is my workflow: [flux-ip-adapter.json](https://github.com/user-attachments/files/16717395/flux-ip-adapter.json)
This is the image for styling used: ![bears](https://github.com/user-attachments/assets/d9a3a387-0e23-4c0e-a087-9b0e62db4e66)

**Comment by viblon1984** [comment]
The same problem happened to me too.

**Comment by jasoncow007** [comment]
same here, cannot work with gguf

**Comment by t00350320** [comment]
> CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors

you bet....  CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors will get this error
