### ISSUE TITLE
(IMPORT FAILED) unsupported Operand. What am I missing here?

### ISSUE THREAD

**Issue by justinwking** [XLabs-AI/x-flux-comfyui#93]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Traceback (most recent call last):
  File "F:\AI\ComfyNew\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 17, in <module>
    from .xflux.src.flux.util import (configs, load_ae, load_clip,
  File "F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui\xflux\src\flux\util.py", line 13, in <module>
    from .model import Flux, FluxParams
  File "F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui\xflux\src\flux\model.py", line 7, in <module>
    from .modules.layers import (DoubleStreamBlock, EmbedND, LastLayer,
  File "F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui\xflux\src\flux\modules\layers.py", line 162, in <module>
    class Modulation(nn.Module):
  File "F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui\xflux\src\flux\modules\layers.py", line 169, in Modulation
    def forward(self, vec: Tensor) -> tuple[ModulationOut, ModulationOut | None]:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Cannot import F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui module for custom nodes: unsupported operand type(s) for |: 'type' and 'NoneType'

Import times for custom nodes:
   0.0 seconds: F:\AI\ComfyNew\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyNew\ComfyUI\custom_nodes\x-flux-comfyui
   0.3 seconds: F:\AI\ComfyNew\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: F:\AI\ComfyNew\ComfyUI\custom_nodes\comfyui_controlnet_aux

**Comment by justinwking** [comment]
I am guessing something is missing, but I'm not sure how to figure it out.

**Comment by Anghellia** [comment]
hi, please send your workflow, so we will reproduce your error and fix it

**Comment by justinwking** [comment]
This error happens at startup, so I am unable to access the Nodes. The error Fails. I'll see if I can clone my comfy ui folder without the models...

**Comment by justinwking** [comment]
Thank you for your advice. After creating a new environment and reinstalling the appropriate requirements, It seems like the modules load at startup.
