### ISSUE TITLE
Manager cannot find nodes ...

### ISSUE THREAD

**Issue by Torcelllo** [XLabs-AI/x-flux-comfyui#99]
... even after ComfyUI update; and a git pull at x-nodes-comfyui

![Capture](https://github.com/user-attachments/assets/f5d13845-ee29-432b-a451-f61b102e763f)

**Comment by Vovanm88** [comment]
Please send logs from comfyui (from console or file comfyui.log)

**Comment by Torcelllo** [comment]
[comfyui.log](https://github.com/user-attachments/files/16798177/comfyui.log)

**Comment by Torcelllo** [comment]
[comfyui.log](https://github.com/user-attachments/files/16798273/comfyui.log)

**Comment by Vovanm88** [comment]
```
Traceback (most recent call last):
  File "X:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\ComfyUI\custom_nodes\x-flux-comfyui\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "X:\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 38, in <module>
    from .clip import FluxClipViT
  File "X:\ComfyUI\custom_nodes\x-flux-comfyui\clip.py", line 3, in <module>
    from transformers import (CLIPImageProcessor,
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1551, in __getattr__
    value = getattr(module, name)
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1550, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\john_\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\import_utils.py", line 1562, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```
Seems like you have incompatible python version and packages, there is system problem, try to follow recommendations in tracelog or reinstall:
Transformers library, via pip: pip install transformers
Python
ComfyUI

**Comment by Torcelllo** [comment]
I installed transformers 2.3.1/cu118, and downgraded protobuf to 3.20.1
It goes to Apply Flux IPAdapter and then this error

![XFlux mat1 and mat2 shapes](https://github.com/user-attachments/assets/37a4bd5b-8105-4230-b2d6-a1f932f76d74)



[comfyui.log](https://github.com/user-attachments/files/16798954/comfyui.log)

**Comment by Vovanm88** [comment]
wrong clip vision i guess

**Comment by Torcelllo** [comment]
When I use the larger one Clip-ViT-14-H-Laion2B-s32B-b79K this error

![Header2Large](https://github.com/user-attachments/assets/21eef046-34fb-491d-b700-219bb93f0410)

**Comment by Vovanm88** [comment]
Use correct clip vision model please ^_^

**Comment by Torcelllo** [comment]
OK, remind me again which is the correct one?

**Comment by Torcelllo** [comment]
Thank you :)

**Comment by Torcelllo** [comment]
Thank you  :)
